
[macd]
optInFastPeriod = 12
optInSlowPeriod = 26
optInSignalPeriod = 9


[macdThresholds]
windowSize = 10
persistence = 1

[rsiPositive]
interval = 10

[rsiNegative]
interval = 6

[rsiThresholds]
low = 20
high = 75
persistence = 1
